/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_nativeopengl_LibraryClass */

#ifndef _Included_com_example_nativeopengl_LibraryClass
#define _Included_com_example_nativeopengl_LibraryClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_nativeopengl_LibraryClass
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_nativeopengl_LibraryClass_init
  (JNIEnv *, jclass);

/*
 * Class:     com_example_nativeopengl_LibraryClass
 * Method:    resize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_nativeopengl_LibraryClass_resize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_nativeopengl_LibraryClass
 * Method:    render
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_nativeopengl_LibraryClass_render
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
